### ISSUE TITLE
Title Bar Has Huge Amount of Extra Space in Some Scenarios

### ISSUE THREAD

**Issue by gwillcox-r7** [tomzorz/Sodalite#1]
In Live Preview Mode which just launched today, if you try open up a Note you get at least a 1/4th of the screen, if not more, taken up by the title bar of the note. This can be seen below:

![Extra Space in Title Note](https://user-images.githubusercontent.com/63261883/141649803-c5294663-9470-4a18-985d-e6c40edc3538.png)

This has occurred in a few other instances but this is the one that I was most easily able to trigger. Any way we could have this adjusted to use reasonable sizes?

**Comment by gwillcox-r7** [comment]
Appears this is being caused by the `Readable Line Length` setting being enabled. I think what is happening is that the tab is expanding to fill the space up to where the start of the text is meant to be inserted. This doesn't happen with the default Obsidian theme which instead just keeps the Title area the same size and just adds whitespace to the editor area on both sides.

**Comment by tomzorz** [comment]
@gwillcox-r7 thank you for reporting, I'll look into it!

**Comment by tomzorz** [comment]
@gwillcox-r7 I can't reproduce this anymore - can you recheck in the latest obsidian version? (0.13.14)

**Comment by gwillcox-r7** [comment]
Confirmed that its the same with most themes in latest Obsidian however this is entirely caused by the `Readable Line Length` option. That being said the arrows on the side are now gone and it seems more natural so I don't think this is a bug, its just a misunderstanding of an existing Obsidian option on my side. 

Will close this out as it isn't a plugin specific issue and seems to be more of a personal preference issue than a theme issue 👍
