### ISSUE TITLE
Notes become left-indent

### ISSUE THREAD

**Issue by AirconLah** [tomzorz/Sodalite#11]
Hi there, I notice that all the notes became left-indent instead of centralized view (default) after I have updated the recent patch of yours. May I know is this on purpose or?

**Comment by tomzorz** [comment]
@AirconLah  oh huh, could you show me with a screenshot what you mean exactly?

**Comment by AirconLah** [comment]
Currently it looks like this:
![Screenshot 2023-05-06 at 1 16 51 PM](https://user-images.githubusercontent.com/93212624/236601694-6a3d9e60-94b1-4288-a7a7-6a22369d630a.png)

Before the upgrade (this is not a solidate theme, but rather to demonstrate the differences):
![Screenshot 2023-05-06 at 1 17 30 PM](https://user-images.githubusercontent.com/93212624/236601720-56bedba8-6e99-439d-88a8-8468dbba9f4b.png)
this before the update:

**Comment by tomzorz** [comment]
Ooooh I see what you mean now. The first picture is how _it used to be_ in my theme until they reworked themes, which broke it. I now changed it back, but I see you prefer the original design with large paddings. 

Hmm, I think I can provide you with a css snippet you can enable to restore that.

**Comment by AirconLah** [comment]
That would be fantastic because I've been used to the original design for a long time and would love to have the original version. 

How can I obtain your CSS snippet? =)

**Comment by tomzorz** [comment]
I'll write it sometime soon™, upload it to the repo and I'll @ you when it's there :)

**Comment by AirconLah** [comment]
Thanks mate! You have been a great help! :)

**Comment by tomzorz** [comment]
@AirconLah sorry it took me a while, but this snippet should make the content 700px wide as your screenshot has it https://github.com/tomzorz/Sodalite/blob/main/snippets/content-max-width-700.css - I've also added a 900px and 1100px version
