### ISSUE TITLE
Title Bar Covers Top of Note

### ISSUE THREAD

**Issue by gilcreque** [tomzorz/Sodalite#2]
Hello. When I use your theme the title bar at the top lays over the top of the note, making it very hard to edit or see anything at the top of the note. I'm on version 0.13.6. Thanks.

![Screen Shot 2021-12-03 at 9 38 58 AM](https://user-images.githubusercontent.com/243234/144621245-1277ff05-de13-4b9e-b609-f66282968f40.png)

**Comment by tomzorz** [comment]
@gilcreque should be fixed by the latest release, thanks for the patience! Please let me know :)

**Comment by gilcreque** [comment]
@tomzorz looks good. Thanks!
