### ISSUE TITLE
All Properties and Outline views have incorrect padding-top for the blur-behind effect

### ISSUE THREAD

**Issue by tomzorz** [tomzorz/Sodalite#25]
Example:

![image](https://github.com/tomzorz/Sodalite/assets/6363312/df9592dc-61b0-4237-aa6c-0f24f0252969)

**Comment by sanchpet** [comment]
How soon will the fix be delivered? 

Switched to your theme, it is very authentic, but this thing keeps irritating me, as I often use the outline while scanning my notes :P

**Comment by tomzorz** [comment]
fixed in 0.8.3

cc @sanchpet

**Comment by sanchpet** [comment]
> fixed in 0.8.3
> 
> cc @sanchpet

That's nice! Thank you very much! Looks perfect now! @tomzorz
