### ISSUE TITLE
How to change the text colour of bold text? 

### ISSUE THREAD

**Issue by JaneValleyhasBtaken** [tomzorz/Sodalite#3]
HI, I just found out that the bold/highlight for me is just too obscure for me. However I love this theme. So I google around and dig into the theme css but didn't find a way to change it. Could you please tell me how to? Thanks.

**Comment by tomzorz** [comment]
Do you mean the text highlight with the == signs?

**Comment by JaneValleyhasBtaken** [comment]
The double asterisk one ( ' ** something ** ' ).

**Comment by JaneValleyhasBtaken** [comment]
Changed the title so no mistakes here

**Comment by tomzorz** [comment]
Aaah I see. So the screenshots are slightly misleading - my theme doesn't change the style of any text content, I'm using snippets for that :D So that's mostly why you can't find code for that in it.

**Comment by tomzorz** [comment]
Here is my font css snippet file https://github.com/tomzorz/obsidian-toolkit/blob/main/snippets/fonts.css - although this doesn't have any styles for bold text either... maybe check out a different theme that does and copy the selectors over 🤔

**Comment by JaneValleyhasBtaken** [comment]
Thanks! I will give a try!
