### ISSUE TITLE
Rework theme for 0.16

### ISSUE THREAD

**Issue by tomzorz** [tomzorz/Sodalite#4]
The latest Obsidian insider version necessitates a complete theme rework - I'll be using this ticket to track the work of that.

**Comment by tomzorz** [comment]
Migration guide: https://forum.obsidian.md/t/0-16-0-theme-migration-guide/42537

**Comment by varpness** [comment]
I'm probably not supposed to post this here and feel free to remove this comment, but I wanted to thank you for your work in creating this theme. I've tried dozens and I still use your theme, even though it's in legacy mode in Obsidian. It fits my needs perfect. Thanks mate!

**Comment by tomzorz** [comment]
@varpness thank you! I do truly appreciate hearing that - and it's definitely motivating to finally get around fixing it hahaha

**Comment by tomzorz** [comment]
Initial update completed! Closing this issue for now - also leaving this here https://forum.obsidian.md/t/1-0-theme-migration-guide/42537
